# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: COWARD RECORDS
email: mail@cowardrecords.com
description: Coward Records ATMOSFERA
url: "http://cowardrecords.com" # the base hostname & protocol for your site
baseurl: ""
links:
 - title: home
   url: /index.html
 - title: releases
   url: /releases
 - title: blog
   url: /blog
 - title: about
   url: /about
 - title: distro
   url: /distro



permalink: /:categories/:title
# Build settings
markdown: kramdown

