# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: COWARD RECORDS
email: mail@cowardrecords.com
description: Coward Records | ATMOSFERA
url: "https://www.cowardrecords.com" # the base hostname & protocol for your site
baseurl: ""

permalink: /:categories/:title/
# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js]

api_key: ODNiZWYzZjUtNGQ4MC00N2NjLThlNzktMDE1ZmQzMzc0YzU5NjM2ODA5MDA4OTg0OTc5NDk4

